# Generated by Django 5.1.3 on 2024-11-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabledit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='date',
            new_name='data',
        ),
    ]
