# Generated by Django 5.1.3 on 2024-12-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabledit', '0005_celldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CellData',
        ),
    ]
