# Generated by Django 5.1.3 on 2024-12-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledit', '0006_delete_celldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('col_id', models.IntegerField()),
                ('value', models.TextField()),
            ],
        ),
    ]
